spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/circle?characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false&failOverReadOnly=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.example.circle.Entity